title: Yantian Zha
description: Personal Webpage
sourcecode: "https://github.com/YantianZha/YantianZha.github.io"

permalink: blog/:year/:month/:day/:title
exclude: ["Makefile", "README.md"]

url: "https://yantianzha.github.io"     # the base hostname & protocol for your site
baseurl: "/yantianzha.github.io"                   # the subpath of your site, e.g. /blog

author:
    name:
    facebook:
    scholar:

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty

# https://github.com/ggreer/jekyll-gallery-generator
plugins:
  - jekyll-gallery-generator

gallery:
  dir: photos               # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Photos"           # Title for gallery index page
  title_prefix: "Photos: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  galleries:
    AAAI19_Honolulu_Hawaii:
      best_image: IMG_20190130_215716.jpg  # The image to show on the gallery index page. Defaults to the last image.
         # Don't show this gallery on the index page. People must guess the URL.
    with_info:
      info:
        desc: "Gallery Description" # Info fields can be used in custom templates.
